import React, { useState, useEffect } from 'react';
import { logout } from '../../services/authService';
import { getTeacherQuizzes, createQuiz, deleteQuiz, getTeacherAnalytics, getTeacherStudents } from '../../services/teacherService';
import { useNavigate } from 'react-router-dom';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { PlusCircle, Activity, Users, LogOut, BookOpen, Trash2, Clock, Calendar } from 'lucide-react';

const TeacherDashboard = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('overview');
  const [quizzes, setQuizzes] = useState([]);
  const [analytics, setAnalytics] = useState({ totalQuizzes: 0, activeStudents: 0, averageScore: 0 });
  const [studentsData, setStudentsData] = useState([]);
  
  const [quizTitle, setQuizTitle] = useState('');
  const [quizTime, setQuizTime] = useState(15);
  const [questions, setQuestions] = useState([]);
  const [creating, setCreating] = useState(false);

  useEffect(() => {
    fetchDashboardData();
  }, []);

  const fetchDashboardData = async () => {
    try {
      const qRes = await getTeacherQuizzes();
      setQuizzes(Array.isArray(qRes.data) ? qRes.data : []);
      
      const aRes = await getTeacherAnalytics();
      setAnalytics(aRes.data);

      const sRes = await getTeacherStudents();
      setStudentsData(Array.isArray(sRes.data) ? sRes.data : []);
    } catch (err) {
      console.error(err);
      setQuizzes([]);
    }
  };

  const handleCreateQuiz = async (e) => {
    e.preventDefault();
    setCreating(true);
    try {
      await createQuiz({
        title: quizTitle,
        description: 'Autogenerated description.',
        timeLimitMinutes: quizTime,
        isPublished: true,
        questions: questions
      });
      setQuizTitle('');
      setQuestions([]);
      setActiveTab('overview');
      fetchDashboardData();
    } catch (err) {
      console.error(err);
    } finally {
      setCreating(false);
    }
  };

  const handleDeleteQuiz = async (quizId) => {
    if (!window.confirm("Are you sure you want to permanently delete this quiz?")) return;
    try {
      await deleteQuiz(quizId);
      fetchDashboardData();
    } catch(err) {
      console.error("Failed to delete quiz:", err);
    }
  };

  const addQuestion = () => {
    setQuestions([
      ...questions, 
      { text: '', type: 'MCQ', options: [{ text: '', isCorrect: true }, { text: '', isCorrect: false }] }
    ]);
  };

  const handleQuestionText = (qIndex, text) => {
    const q = [...questions];
    q[qIndex].text = text;
    setQuestions(q);
  };

  const chartData = studentsData.length > 0 
    ? studentsData.map(s => ({ name: s.studentName.split('@')[0], avgScore: s.quizzesTaken ? Math.round(s.totalScore / s.quizzesTaken) : 0 }))
    : [{ name: 'No Data', avgScore: 0 }];

  return (
    <div style={{ display: 'flex', minHeight: '100vh' }}>
      <div className="glass-panel" style={{ width: '250px', margin: '1rem', display: 'flex', flexDirection: 'column' }}>
        <h2 style={{ marginBottom: '2rem', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <BookOpen /> Teacher
        </h2>
        
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', flex: 1 }}>
          <button className={`btn ${activeTab !== 'overview' && 'btn-secondary'}`} onClick={() => setActiveTab('overview')}>
            <Activity size={18} style={{ marginRight: '8px', verticalAlign: 'middle' }}/> Overview
          </button>
          <button className={`btn ${activeTab !== 'builder' && 'btn-secondary'}`} onClick={() => setActiveTab('builder')}>
            <PlusCircle size={18} style={{ marginRight: '8px', verticalAlign: 'middle' }}/> Create Quiz
          </button>
          <button className={`btn ${activeTab !== 'live' && 'btn-secondary'}`} onClick={() => setActiveTab('live')}>
            <Activity size={18} style={{ marginRight: '8px', verticalAlign: 'middle' }}/> Live Arena
          </button>
          <button className={`btn ${activeTab !== 'students' && 'btn-secondary'}`} onClick={() => setActiveTab('students')}>
            <Users size={18} style={{ marginRight: '8px', verticalAlign: 'middle' }}/> Students
          </button>
        </div>

        <button className="btn btn-secondary" style={{ border: 'none' }} onClick={() => { logout(); navigate('/login'); }}>
          <LogOut size={18} style={{ marginRight: '8px', verticalAlign: 'middle', color: '#ff4757' }}/> Logout
        </button>
      </div>

      <div style={{ flex: 1, padding: '1rem', overflowY: 'auto' }}>
        <div className="glass-panel" style={{ minHeight: 'calc(100vh - 2rem)' }}>
          {activeTab === 'overview' && (
            <div style={{ animation: 'fadeIn 0.5s ease' }}>
              <h2 style={{ marginBottom: '1.5rem', fontWeight: 600 }}>Dashboard Overview</h2>
              
              <div style={{ display: 'flex', gap: '2rem', marginBottom: '2.5rem' }}>
                <div className="glass-panel glass-card" style={{ flex: 1, padding: '1.5rem', background: 'rgba(255,255,255,0.02)' }}>
                  <h3 style={{ margin: 0, fontSize: '1rem', color: 'var(--text-muted)' }}>Created Quizzes</h3>
                  <p style={{ margin: '10px 0 0 0', fontSize: '2.5rem', fontWeight: 'bold', color: 'var(--primary-color)' }}>{analytics.totalQuizzes}</p>
                </div>
                <div className="glass-panel glass-card" style={{ flex: 1, padding: '1.5rem', background: 'rgba(255,255,255,0.02)' }}>
                  <h3 style={{ margin: 0, fontSize: '1rem', color: 'var(--text-muted)' }}>Active Students</h3>
                  <p style={{ margin: '10px 0 0 0', fontSize: '2.5rem', fontWeight: 'bold', color: '#1dd1a1' }}>{analytics.activeStudents}</p>
                </div>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)', gap: '2rem', marginBottom: '3rem' }}>
                <div>
                  <h3 style={{ fontWeight: 500, marginBottom: '1rem' }}>Student Average Scores</h3>
                  <div style={{ height: '300px' }}>
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={chartData}>
                        <XAxis dataKey="name" stroke="#a4b0be" axisLine={false} tickLine={false} />
                        <YAxis stroke="#a4b0be" axisLine={false} tickLine={false} />
                        <Tooltip 
                          contentStyle={{ background: 'rgba(0,0,0,0.8)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }}
                          cursor={{fill: 'rgba(255,255,255,0.05)'}}
                        />
                        <Bar dataKey="avgScore" fill="var(--primary-color)" radius={[6, 6, 0, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                </div>

                <div>
                  <h3 style={{ fontWeight: 500, marginBottom: '1rem' }}>Category-wise Accuracy</h3>
                  <div style={{ height: '300px' }}>
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={analytics.categoryAccuracy ? Object.entries(analytics.categoryAccuracy).map(([name, accuracy]) => ({ name, accuracy })) : []}>
                        <XAxis dataKey="name" stroke="#a4b0be" axisLine={false} tickLine={false} />
                        <YAxis stroke="#a4b0be" axisLine={false} tickLine={false} />
                        <Tooltip 
                          contentStyle={{ background: 'rgba(0,0,0,0.8)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }}
                          cursor={{fill: 'rgba(255,255,255,0.05)'}}
                        />
                        <Bar dataKey="accuracy" fill="#1dd1a1" radius={[6, 6, 0, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                </div>
              </div>

              <h3 style={{ fontWeight: 600, marginBottom: '1.5rem' }}>Your Published Quizzes</h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                {quizzes.length === 0 ? (
                  <div style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-muted)', background: 'rgba(0,0,0,0.2)', borderRadius: '15px' }}>
                    <p style={{ fontSize: '1.2rem', marginBottom: '1rem' }}>You haven't built any quizzes yet!</p>
                    <button className="btn" onClick={() => setActiveTab('builder')}>Start Building</button>
                  </div>
                ) : (
                  quizzes.map(quiz => (
                    <div key={quiz.id} className="glass-panel glass-card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem', background: 'rgba(0,0,0,0.2)' }}>
                      <div>
                        <h4 style={{ margin: '0 0 8px 0', fontSize: '1.3rem', color: 'white' }}>{quiz.title}</h4>
                        <div style={{ display: 'flex', gap: '20px', color: 'var(--text-muted)', fontSize: '0.95rem' }}>
                          <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Clock size={14}/> {quiz.timeLimitMinutes} mins</span>
                          <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Activity size={14}/> {quiz.questions?.length || 0} Questions</span>
                          <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Calendar size={14}/> Published {new Date(quiz.createdAt).toLocaleDateString()}</span>
                        </div>
                      </div>
                      <div style={{ display: 'flex', gap: '10px' }}>
                        <button 
                          className="btn" 
                          onClick={() => handleDeleteQuiz(quiz.id)}
                          style={{ background: 'rgba(255, 71, 87, 0.1)', border: '1px solid var(--primary-color)', color: 'var(--primary-color)', display: 'flex', alignItems: 'center', gap: '5px' }}
                        >
                          <Trash2 size={16} /> Remove
                        </button>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}

          {activeTab === 'builder' && (
            <div style={{ animation: 'fadeIn 0.5s ease', maxWidth: '800px', margin: '0 auto' }}>
              <h2 style={{ marginBottom: '2rem', fontWeight: 600 }}>Create New Interactive Quiz</h2>
              <form onSubmit={handleCreateQuiz}>
                <label style={{ display: 'block', marginBottom: '5px', color: 'var(--text-muted)' }}>Quiz Title</label>
                <input className="input-field" placeholder="e.g. Advanced JavaScript Concepts" value={quizTitle} onChange={e => setQuizTitle(e.target.value)} required />
                
                <label style={{ display: 'block', marginBottom: '5px', color: 'var(--text-muted)' }}>Configuration</label>
                <input className="input-field" type="number" placeholder="Time Limit (minutes)" value={quizTime} onChange={e => setQuizTime(e.target.value)} required />
                
                <div style={{ margin: '2rem 0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <h3 style={{ margin: 0, fontWeight: 500 }}>Questions</h3>
                  <button type="button" className="btn" onClick={addQuestion} style={{ background: '#341f97', display: 'flex', alignItems: 'center', gap: '5px' }}>
                    <PlusCircle size={16}/> Add Question
                  </button>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                  {questions.map((q, qIndex) => (
                    <div key={qIndex} className="glass-panel" style={{ padding: '1.5rem', background: 'rgba(0,0,0,0.15)' }}>
                      <h4 style={{ marginBottom: '10px', color: 'var(--primary-color)' }}>Question {qIndex + 1}</h4>
                      <input className="input-field" placeholder={`Enter question text here...`} value={q.text} onChange={e => handleQuestionText(qIndex, e.target.value)} required />
                      
                      <div style={{ paddingLeft: '1rem', marginTop: '1rem' }}>
                        <label style={{ display: 'block', marginBottom: '10px', color: 'var(--text-muted)', fontSize: '0.9rem' }}>Answers (select the correct one):</label>
                        {q.options.map((opt, oIndex) => (
                          <div key={oIndex} style={{ display: 'flex', gap: '15px', marginBottom: '10px', alignItems: 'center' }}>
                            <input 
                              type="radio" 
                              checked={opt.isCorrect} 
                              onChange={() => {
                                const qs = [...questions];
                                qs[qIndex].options.forEach(o => o.isCorrect = false);
                                qs[qIndex].options[oIndex].isCorrect = true;
                                setQuestions(qs);
                              }}
                              style={{ transform: 'scale(1.2)', accentColor: 'var(--primary-color)' }}
                            />
                            <input 
                              className="input-field" 
                              style={{ margin: 0, background: opt.isCorrect ? 'rgba(255, 71, 87, 0.1)' : '', borderColor: opt.isCorrect ? 'var(--primary-color)' : '' }} 
                              placeholder={`Option ${oIndex + 1}`} 
                              value={opt.text} 
                              onChange={(e) => {
                                const qs = [...questions];
                                qs[qIndex].options[oIndex].text = e.target.value;
                                setQuestions(qs);
                              }} 
                              required 
                            />
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
                
                {questions.length > 0 && (
                  <button type="submit" className="btn" disabled={creating} style={{ width: '100%', marginTop: '3rem', fontSize: '1.2rem', padding: '1rem' }}>
                    {creating ? 'Publishing to Database...' : '🚀 Publish Quiz Successfully'}
                  </button>
                )}
              </form>
            </div>
          )}

          {activeTab === 'students' && (
            <div style={{ animation: 'fadeIn 0.5s ease' }}>
              <h2 style={{ marginBottom: '1.5rem' }}>Student Progress Management</h2>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                {studentsData.length === 0 ? (
                  <div className="glass-panel" style={{ textAlign: 'center', padding: '4rem', background: 'rgba(0,0,0,0.1)' }}>
                     <Users size={64} style={{ opacity: 0.3, marginBottom: '1rem' }} />
                     <p style={{ color: 'var(--text-muted)', fontSize: '1.1rem' }}>No student data available yet.</p>
                  </div>
                ) : (
                  studentsData.map(student => (
                    <div key={student.studentId} className="glass-panel glass-card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem', background: 'rgba(0,0,0,0.2)' }}>
                      <div>
                        <h4 style={{ margin: '0 0 8px 0', fontSize: '1.3rem', color: 'white' }}>{student.studentName}</h4>
                        <div style={{ display: 'flex', gap: '20px', color: 'var(--text-muted)', fontSize: '0.95rem' }}>
                          <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Activity size={14}/> {student.quizzesTaken} Quizzes Taken</span>
                        </div>
                      </div>
                      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end' }}>
                        <span style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>Total Score</span>
                        <span style={{ fontSize: '1.8rem', fontWeight: 'bold', color: '#1dd1a1' }}>{student.totalScore}</span>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}

          {activeTab === 'live' && (
            <div style={{ animation: 'fadeIn 0.5s ease', maxWidth: '600px', margin: '0 auto', textAlign: 'center', paddingTop: '3rem' }}>
              <div className="glass-panel" style={{ padding: '3rem', background: 'rgba(0,0,0,0.2)' }}>
                <Activity size={64} color="#fbc531" style={{ marginBottom: '1rem' }} />
                <h2 style={{ marginBottom: '1rem' }}>Host a Live Quiz Event</h2>
                <p style={{ color: 'var(--text-muted)', marginBottom: '2rem' }}>Launch a real-time multiplayer arena. Students can join via a unique room code.</p>
                
                <button 
                  className="btn" 
                  onClick={() => {
                    const roomId = Math.floor(1000 + Math.random() * 9000).toString();
                    navigate(`/live/${roomId}`);
                  }}
                  style={{ fontSize: '1.2rem', padding: '1rem 2rem', background: 'var(--primary-color)' }}
                >
                  🚀 Generate Link & Start Hosting
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default TeacherDashboard;
